{{- if .Values.role.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "camunda.fullname" . }}
  labels:
    {{- include "camunda.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - apps
      - ""
    resources:
      - deployments
      - pods
    verbs:
      - get
      - list
      - update
  {{- end }}