apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: camunda-deployment
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camunda-deployment
  metrics:
    - type: Pods
      pods:
        metric:
          name: camunda_processes_started_per_instance
        target:
          type: AverageValue
          averageValue: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 40
          periodSeconds: 10
        - type: Pods
          value: 1
          periodSeconds: 10
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10