apiVersion: v1
kind: Service
metadata:
  name: camunda-service
spec:
  selector:
    app: camunda
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-deployment
  labels:
    app: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
     - image: avguston/camunda-metric:0.1.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8088
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: metric
        ports:
        - containerPort: 8088
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8088
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - name: camunda
        image: camunda/camunda-bpm-platform:tomcat-latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DB_DRIVER
          value: org.postgresql.Driver
        - name: DB_URL
          value: jdbc:postgresql://db:5432/process-engine
        - name: DB_USERNAME
          value: camunda
        - name: DB_PASSWORD
          value: camunda
        - name: DB_VALIDATE_ON_BORROW
          value: "true"
        - name: WAIT_FOR
          value: db:5432
        livenessProbe:
          httpGet:
            path: /camunda
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /camunda
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

