apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-process-starter
  labels:
    app: process-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process-starter
  template:
    metadata:
      labels:
        app: process-starter
    spec:
      containers:
      - name: process-starter
        image: andreagiardini/camunda_process_starter
        env:
        - name: CAMUNDA_HOST
          value: "camunda-service:8080"
        - name: N_PROCESS_STARTED
          value: "50"
        - name: QUIET_TIME_S
          value: "10"
