---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: camunda
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camunda
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: camunda
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
